### ISSUE TITLE
Error when processing big files

### ISSUE THREAD

**Issue by Joost1991** [javi11/usenet-drive#127]
When uploading big files (> 20GB) I regulary get errors like this:

```
{"time":"2024-03-29T13:12:16.809330105Z","level":"INFO","msg":"File uploaded","name":"/nzbs/file.mkv","size":20268283366}
{"time":"2024-03-29T13:12:17.813938742Z","level":"ERROR","msg":"Error removing corrupted nzb from list","error":"sql: no rows in result set"}
```

It ends up in a loop where it uploads the file over and over again. 

Let me know if you need anymore information.

**Comment by javi11** [comment]
Do you use rclone vfs cache for uploading? for the moment chunk upload is not possible so you will need to mount the remote with rclone using the vfs cache in order that your upload is first cached by rclone and then uploaded at once.

**Comment by Joost1991** [comment]
I do use VFS cache with rclone, yes. Mounting it as follows;

```
rclone mount --allow-other --async-read=true --dir-cache-time=1000h --buffer-size=32M --poll-interval=15s --use-mmap --vfs-read-ahead=128M --vfs-read-chunk-size=32M --vfs-read-chunk-size-limit=2G --vfs-cache-max-age=504h --vfs-cache-mode=full --vfs-cache-poll-interval=30s --vfs-cache-max-size=50G --timeout=10m --umask=002 --cache-dir cache-usenet  --log-file logs/rclone-usenet.log --crypt-suffix none --daemon usenet-crypt: usenet
```

**Comment by javi11** [comment]
Okey I will need to check then ;)

**Comment by MythodeaLoL** [comment]
Tested on Windows 11 x64 using [improve-download-speed ](https://github.com/javi11/usenet-drive/tree/improve-download-speed)
25GB mkv file, nzb:
```
    <meta type="file_size">26463186475</meta>
    <meta type="mod_time">2024-03-29 17:06:32</meta>
    <meta type="file_extension">.mkv</meta>
    <meta type="file_name">REDACTED.mkv</meta>
    <meta type="chunk_size">3145728</meta>
```

Debug Log:
```
{"time":"2024-03-29T14:58:10.2583224-03:00","level":"DEBUG","msg":"WebDav error","err":"mkdir G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB: Não é possível criar um arquivo já existente."}
{"time":"2024-03-29T14:58:10.4183254-03:00","level":"INFO","msg":"Uploading file","name":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED.mkv","size":26463186475}
{"time":"2024-03-29T15:13:45.2776016-03:00","level":"INFO","msg":"Upload finished successfully.","filename":"REDACTED.mkv"}
{"time":"2024-03-29T15:13:45.2776016-03:00","level":"INFO","msg":"File uploaded","name":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED.mkv","size":26463186475}
```

Using rclone VFS, same configs as (https://github.com/javi11/usenet-drive/issues/121#issuecomment-2016538252)

**No problems found.**

**Comment by Joost1991** [comment]
Got some other failing files... again quite big files.

```
{"time":"2024-03-29T19:12:54.899596304Z","level":"INFO","msg":"File uploaded","name":"<<REDACTED>>","size":17514523499}
{"time":"2024-03-29T19:12:55.90612058Z","level":"ERROR","msg":"Error removing corrupted nzb from list","error":"sql: no rows in result set"}
{"time":"2024-03-29T19:12:55.939606008Z","level":"INFO","msg":"Uploading file","name":"<<REDACTED>>","size":17514523499}
```

**Comment by MythodeaLoL** [comment]
@Joost1991 
what operating system are you using?
what version of usenet-drive are you using?
the information is a bit vague to help, since the project is in dev, and the most stable version is `improve-download-speed`, the main version is partially stable, but it contains some problems that have already been fixed, just compile the latest version `improve-download-speed`.

The more information you can provide when reporting a problem, the more likely you are to have it resolved.
It's a good idea to always include the heap file, download it from http://localhost:8081/debug/pprof/heap, and send it zipped.

Here I tested with files larger than 30GB and didn't get any problems in the version `improve-download-speed`.

**Comment by Joost1991** [comment]
I am running it on a linux machine, Ubuntu 22.04. I'm using the default `article_size_in_bytes` value, so changes in that.

I did run it on the `main` branch. So I'm now trying it out on the `improve-download-speed` branch to see if that helps.

**Comment by Joost1991** [comment]
Doesn't seem to matter. 

Still having the same issue with the `improve-download-speed` branch. 

I include the heap.

[heap-reupload-error.zip](https://github.com/javi11/usenet-drive/files/14813337/heap-reupload-error.zip)

**Comment by drondeseries** [comment]
> Doesn't seem to matter.
> 
> Still having the same issue with the `improve-download-speed` branch.
> 
> I included the heap.
> 
> [heap-reupload-error.zip](https://github.com/javi11/usenet-drive/files/14813337/heap-reupload-error.zip)

Having the same errors.
Can you post your usenet config ?

**Comment by Joost1991** [comment]
Just experienced it happening to some smaller files as well (4-5GB).

So I think something triggers it, but not sure what.

**Comment by javi11** [comment]
@Joost1991 could you please post your config?

**Comment by Joost1991** [comment]
Config.yaml

```
root_path: /nzbs
webdav_port: 8080
api_port: 8081
db_path: /config/usenet-drive.db
usenet:
  download:
    max_download_workers: 5
    providers:
      - host: redacted
        port: 563
        username: redacted
        password: redacted
        tls: true
        max_connections: 25
  upload:
    groups:
      - alt.binaries.test
    file_allow_list:
      - .mkv
      - .mp4
      - .avi
      - .ts
    providers:
      - host: redacted
        port: 563
        username: redacted
        password: redacted
        tls: true
        max_connections: 25
```
