### ISSUE TITLE
Docker: /usenet-drive: not found

### ISSUE THREAD

**Issue by Aerya** [javi11/usenet-drive#76]
Hi,

Trying to test using Docker:
```version: "3.8"
services:
  usenet-drive:
    image: laris11/usenet-drive:latest
    container_name: UsenetDrive
    restart: always
    command: /usenet-drive -c /config/config.yaml
    ports:
      - 2024:8080
      - 2025:8081
    volumes:
      - /mnt/user/appdata/UsenetDrive:/config
      - /mnt/PRE/nzbs:/nzbs
    environment:
      - PUID=1000
      - PGID=1000
```
But got an error: 
```
UsenetDrive  | 
UsenetDrive  | To support LSIO projects visit:
UsenetDrive  | https://www.linuxserver.io/donate/
UsenetDrive  | 
UsenetDrive  | ───────────────────────────────────────
UsenetDrive  | GID/UID
UsenetDrive  | ───────────────────────────────────────
UsenetDrive  | 
UsenetDrive  | User UID:    1000
UsenetDrive  | User GID:    1000
UsenetDrive  | ───────────────────────────────────────
UsenetDrive  | 
UsenetDrive  | [custom-init] No custom files found, skipping...
UsenetDrive  | [ls.io-init] done.
UsenetDrive  | /run/s6/basedir/scripts/rc.init: 76: /usenet-drive: not found
```

Any advise?
Thanks

**Comment by javi11** [comment]
Hi thanks for reporting, could you paste the content of the docker container? Also, could you use the version v0.0.71, the last version has a bug.

Be aware that this project is still in beta phase so there are some bugs yet, still is 100% usable :)

**Comment by Aerya** [comment]
Thanks but same error using v0.0.71

```
# ls -l / 
total 20404
drwxr-xr-x   1 abc  abc         0 Dec 19 23:28 app
lrwxrwxrwx   1 root root        7 Dec 19 23:27 bin -> usr/bin
drwxr-xr-x   1 root root        0 Apr 18  2022 boot
drwxr-xr-x   1 root root     5272 Dec 19 23:27 command
drwxrwxrwx   1 abc  abc        25 Jan 15 05:40 config
drwxr-xr-x   1 abc  abc         0 Dec 19 23:28 defaults
drwxr-xr-x   5 root root      340 Jan 15 05:40 dev
-rwxr--r--   1 root root    18909 Jan  1  1970 docker-mods
drwxr-xr-x   1 root root     1544 Jan 15 05:40 etc
drwxr-xr-x   1 root root        0 Apr 18  2022 home
-rwxr-xr-x   1 root root      907 May  4  2023 init
lrwxrwxrwx   1 root root        7 Dec 19 23:27 lib -> usr/lib
lrwxrwxrwx   1 root root        9 Dec 19 23:27 lib32 -> usr/lib32
lrwxrwxrwx   1 root root        9 Dec 19 23:27 lib64 -> usr/lib64
lrwxrwxrwx   1 root root       10 Dec 19 23:27 libx32 -> usr/libx32
drwxr-xr-x   1 root root        0 Dec 19 23:28 lsiopy
drwxr-xr-x   1 root root        0 Jun 26  2023 media
drwxr-xr-x   1 root root        0 Jun 26  2023 mnt
drwxrwxrwx   2 root root       40 Jan 14 17:36 nzbs
drwxr-xr-x   1 root root        0 Jun 26  2023 opt
drwxr-xr-x   1 root root       30 Dec 19 23:27 package
dr-xr-xr-x 641 root root        0 Jan 15 05:40 proc
drwx------   1 root root       30 Dec 19 23:27 root
drwxr-xr-x   1 root root      168 Jan 15 05:40 run
lrwxrwxrwx   1 root root        8 Dec 19 23:27 sbin -> usr/sbin
drwxr-xr-x   1 root root        0 Jun 26  2023 srv
dr-xr-xr-x  13 root root        0 Jan 15 05:40 sys
drwxrwxrwt   1 root root        0 Dec 19 23:28 tmp
-rwxr-xr-x   1 root root 20840192 Dec 21 08:41 usenetdrive
drwxr-xr-x   1 root root      116 May  4  2023 usr
drwxr-xr-x   1 root root       90 Dec 19 23:27 var
```

**Comment by javi11** [comment]
@Aerya It solves your issue?

**Comment by Aerya** [comment]
Hi, sorry due to lack of time I couldn't give it a try earlier. It seems to work.
I'm looking at using it now ^^' 

I'm note sure how it works.
I created an rClone WebDav remote "Usenet" and its crypted remote "UsenetCrypt" as i usually did with Clouds for years. I followed your specs about it.

I mounted the UsenetCrypt remote. 

I ran UsenetDrive using Docker and this config:
```
root_path: /nzbs
webdav_port: 8080
api_port: 8081
db_path: /config/usenet-drive.db
vfs_url: http://localhost:7579
usenet:
  download:
    max_ahead_download_segments: 2
    max_cache_size_in_mb: 1024
    providers:
      - host: news.eweka.nl
        port: 563
        username: user
        password: pwd
        ssl: true
        max_connections: 30
  upload:
    groups:
      - group1
      - group2
    file_allow_list:
      - .*
      - .*.bin
    providers:
      - host: news.eweka.nl
        port: 563
        username: user
        password: pwd
        ssl: true
        max_connections: 50
```

I got the WebUI running nice.

I used a script to rClone move files to my UsenetCrypt remote. Nothing happened then. It seems I don't understand how to use your work.

**Comment by javi11** [comment]
NP ;). Do you see logs for it? 

I think it has to be with the file_allow_list glob pattern is not supported yet, since you are using rclone crypt you can simply use .bin as all files will have that extension

Regarding connections, remember that you need to share download and upload connections so for instance if you have 100 connections it´s important to share 50/50 for upload and download since if you put 100 connection on both you will end up with max connection reached errors. Remember that for upload all connections are used

Hopes that this helps ,)

**Comment by javi11** [comment]
Hi, .mkv.bin should work you have some log or something? Could you also post your config. Usage of the package it might be kind of difficult, hope to improve it on the future

**Comment by Aerya** [comment]
Here we go, hope you'll help me understand what is my mistake ;)

The compose
```
version: "3"
services:
  usenet-drive:
    image: laris11/usenet-drive:v0.0.71
    container_name: UsenetDrive
    restart: always
    command: /usenetdrive -c /config/config.yaml
    ports:
      - 2024:8080
      - 2025:8081
    volumes:
      - /mnt/user/appdata/UsenetDrive:/config
      - /mnt/user/PRE/nzbs:/nzbs
    environment:
      - PUID=1000
      - PGID=1000
```

Config.yaml
```
root_path: /nzbs
webdav_port: 8080
api_port: 8081
db_path: /config/usenet-drive.db
vfs_url: http://localhost:7579
usenet:
  download:
    max_ahead_download_segments: 2
    max_cache_size_in_mb: 1024
    providers:
      - host: news.eweka.nl
        port: 563
        username: user
        password: pwd
        ssl: true
        max_connections: 25
  upload:
    groups:
      - alt.binaries.boneless
      - alt.binaries.boneless.nl
    file_allow_list:
      - .mkv.bin
      - .*.bin
    providers:
      - host: news.eweka.nl
        port: 563
        username: user
        password: pwd
        ssl: true
        max_connections: 25
```

rClone config
```
[Usenet]
type = webdav
url = http://localhost:2024
vendor = other

[UsenetCrypt]
type = crypt
remote = Usenet:
filename_encryption = off
directory_name_encryption = false
password = xxx
```
rClone mount
```
#!/bin/bash
rclone mount UsenetCrypt: /mnt/user/UsenetCrypt \
--allow-other \
--allow-non-empty \
--async-read=true \
--buffer-size=32M \
--poll-interval=15s \
--rc \
--rc-no-auth \
--rc-addr=localhost:5572 \
--dir-cache-time 24h \
--use-mmap \
--vfs-read-ahead=128M \
--vfs-read-chunk-size=32M \
--vfs-read-chunk-size-limit=2G \
--vfs-cache-max-age=504h \
--vfs-cache-mode=full \
--vfs-cache-poll-interval=30s \
--vfs-cache-max-size=50G \
--timeout=10m \
--log-level INFO \
--log-file /mnt/user/docs/UsenetCrypt.log \
--umask 002 \
--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
```

=>
```
root@HomeBox:/# df -H
Filesystem                                                   Size  Used Avail Use% Mounted on
UsenetCrypt:                                                 1.2P     0  1.2P   0% /mnt/user/UsenetCrypt
```

rClone move script (useless I guess? so tried it but then set it off)
```
#!/bin/bash
LOG="/mnt/user/docs/rclone.log"
EXC1="/SD/**"
EXC2="/Ratio/**"
EXC3="/PreSeries/**"
EXC4="/PreFilms/**"
EXC5="/PreComics/**"
EXC6="/Stuff/**"

if pidof -o %PPID -x "$0"; then
   exit 1
fi
sleep 30
while true
do
  echo "$(date "+%d.%m.%Y %T") RCLONE UPLOAD STARTED" | tee -a "$LOG"
rclone move -c -v --copy-links \
--exclude='**partial~' --exclude="**_HIDDEN~" \
--exclude=".unionfs/**" --exclude=".fuse_hidden*" \
--exclude="$EXC1" --exclude="$EXC2" \
--exclude="$EXC3" --exclude="$EXC4" \
--exclude="$EXC5" --exclude="$EXC6" \
--min-age=5m \
--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" \
--transfers=10 --checkers=10 --stats 5s \
--log-file="$LOG" /mnt/user/PRE UsenetCrypt:/
sleep 480
  echo "$(date "+%d.%m.%Y %T") RCLONE UPLOAD ENDED" | tee -a "$LOG"
done
```

/nzbs content
```
root@HomeBox:/mnt/user/PRE/nzbs# tree
.
└── Documentaires
    └── Hackers.L.intimite.violee.2023.DOC.FRENCH.1080p.WEB.x264-FW
        └── Hackers.L.intimite.violee.2023.DOC.FRENCH.1080p.WEB.x264-FW.mkv.bin

3 directories, 1 file
```

usenet-drive logs
https://pastebin.com/Q4UyXjuw
