### ISSUE TITLE
[BUG] Completely incorrect connection handling with usenight.com provider

### ISSUE THREAD

**Issue by gyurix** [javi11/usenet-drive#91]
If you try to use the software with the https://usenight.com provider, you will see that after a few minutes of active uploading a bunch of ghost connections gets created and the program stops working because of hitting the 50 connection limit of the provider, despite the fact of being limited to much less connections in the config. This provider is a very solid one supporting insanely high speeds, even in the range of 5-10Gbps for extremely cheap, so it will be great to see this tool work with them properly.

**Comment by javi11** [comment]
@gyurix could you put the log that shows the error? Probably if you hit max connections a code 502 will appear on the logs

**Comment by gyurix** [comment]
Yes, it shows up in the logs:
```
{"time":"2024-02-04T00:59:11.366235079Z","level":"ERROR","msg":"Error uploading the file","filename":"OMITTED","error":"error getting nntp connection: 482 too many connections for your user"}
{"time":"2024-02-04T00:59:11.36628115Z","level":"INFO","msg":"Upload file was discarded because an error","name":"OMITTED","err":"error getting nntp connection: 482 too many connections for your user"}
```

The easiest way to reproduce the error is to start uploading some files using rclone copy and once finished start another upload with rclone copy.

My config looks like this (with valid credentials of course):
```
root_path: /nzbs
webdav_port: 8080
api_port: 8081
db_path: /config/usenet-drive.db
usenet:
  download:
    max_download_workers: 3
    providers:
      - host: "reader.usenight.com"
        port: 563
        username: "OMITTED"
        password: "OMITTED"
        tls: true
        max_connections: 3
  upload:
    groups:
      - alt.binaries
    file_allow_list:
      - .bin
    providers:
      - host: "reader.usenight.com"
        port: 563
        username: "OMITTED"
        password: "OMITTED"
        tls: true
        max_connections: 27
```
